language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install pytest-cov
  - pip install codecov
  - travis_wait mvn install
# command to run tests
env:
    - CODECOV_TOKEN=<c0f8e244-ce0a-431b-a5ce-2a8a8a2faf48>
script:
  - python -m pytest --cov=py_ev
after_success:
  - codecov
