language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install pytest-cov
# command to run tests
script:
  - pytest
  - pytest --cov=./
after_success:
  - bash < (curl -s https://codecov.io/bash)
